name: ejemplo1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  flame: any
  shared_preferences: any
  flutter_confetti: any 
  loading_animation_widget: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any  

dependency_overrides:
  characters: any
  collection: any
  material_color_utilities: any
  meta: any
  async: any
  boolean_selector: any
  fake_async: any
  leak_tracker: any
  leak_tracker_flutter_testing: any
  lints: any
  matcher: any
  path: any
  stack_trace: any
  string_scanner: any
  test_api: any
  vm_service: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/tiles/

flutter_native_splash:
  color: "#042B59"
  image: assets/images/splash.png

flutter_icons:
 android: true
 ios: true
 image_path: "assets/images/launcher.png"